$(document).ready(function(){
	$('.owl-carousel').owlCarousel({
	    loop:true,
	    margin:15,
	    nav:true,
	    responsive:{
	        0:{
	            items:1
	        },
	        1000:{
	            items:3
	        },
	        1500:{
	            items:5
	        }
	    }
	})
});

